# test file is created in all different services to run tests in parallel 
name: tests-orders

# if there is a new pull request or a pull request gets reopen
# and and the files changes are located in '<serviceName>/**'
# then run this specified job
on:
  pull_request:
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
