# test file is created in all different services to run tests in parallel 
name: tests-payments

# if there is a new pull request or a pull request gets reopen
# and and the files changes are located in '<serviceName>/**'
# then run this specified job
on:
  pull_request:
    paths:
      - "payments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
